

const districts = {
    "Uttar Pradesh": {
        "Lucknow": ["King George’s Medical University (KGMU) Blood Bank", "Aarogyam Blood Bank","Red Cross Society Blood Bank","Lala Lajpat Rai Memorial Blood Bank","Blood Bank at Civil Hospital","Bharat Blood Bank"],
        "Kanpur": ["Kanpur Blood Bank", "Sri Ram Murti Smarak Blood Bank","Kalyan Blood Bank","Apex Blood Bank","Shree Sai Blood Bank"],
        "Varanasi": ["Sri Sankaracharya Blood Bank", "Blood Bank - BHU (Banaras Hindu University)","Kashi Blood Bank","Shree Vishwanath Blood Bank","Rotary Blood Bank"],
        "Agra": ["Agra Blood Bank", "Red Cross Blood Bank","Rajasthan Blood Bank","Indian Red Cross Society Blood Bank","J.K. Hospital Blood Bank"],
        "Noida": ["Noida Blood Bank", "Apollo Hospital Blood Bank","Fortis Hospital Blood Bank","Max Super Speciality Hospital Blood Bank","Bramh Kumari’s Blood Donation Camp","Sharda Hospital Blood Bank","DRDO Blood Bank"],
        "Aligarh": ["J.N. Medical College Blood Bank","Sarojini Naidu Medical College Blood Bank","Aligarh Muslim University Blood Bank","Red Cross Society Blood Bank","Aligarh District Hospital Blood Bank"],
        "Allahabad (Prayagraj)": ["Blood Bank - S.R.N. Hospital", "Allahabad Medical Association Blood Bank", "Red Cross Society Blood Bank", "M.L.N. Medical College Blood Bank", "Prayag Blood Bank"],
        "Ambedkar Nagar": ["Ambedkar Nagar District Hospital Blood Bank", "Red Cross Society Blood Bank", "Babu Saran Blood Bank"],
        "Amethi": ["Amethi District Hospital Blood Bank", "Red Cross Society Blood Bank", "Shree Ganesh Blood Bank"],
        "Amroha": ["Amroha District Hospital Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
        "Auraiya": ["Auraiya District Hospital Blood Bank", "Red Cross Society Blood Bank", "Shree Radha Blood Bank"],
        "Ayodhya (Faizabad)": ["Ayodhya District Hospital Blood Bank", "Red Cross Society Blood Bank", "Shree Ram Blood Bank"],
        "Azamgarh": ["Azamgarh District Hospital Blood Bank", "Red Cross Society Blood Bank", "Shree Ganesh Blood Bank"],
        "Baghpat": ["Baghpat District Hospital Blood Bank", "Red Cross Society Blood Bank", "Sai Blood Bank"],
        "Bahraich": ["Bahraich District Hospital Blood Bank", "Red Cross Society Blood Bank", "Shree Ram Blood Bank"],
        "Ballia": ["Ballia District Hospital Blood Bank", "Red Cross Society Blood Bank", "Shree Vishnu Blood Bank"],
        "Balrampur": ["Balrampur District Hospital Blood Bank", "Red Cross Society Blood Bank", "Shree Ram Blood Bank"],
        "Banda": ["Banda District Hospital Blood Bank", "Red Cross Society Blood Bank", "Shree Ganesh Blood Bank"],
        "Barabanki": ["Barabanki District Hospital Blood Bank", "Red Cross Society Blood Bank", "Shree Vishnu Blood Bank"],
        "Bareilly": ["Bareilly District Hospital Blood Bank", "Red Cross Society Blood Bank", "Sai Blood Bank"],
        "Basti": ["Basti District Hospital Blood Bank", "Red Cross Society Blood Bank", "Shree Vishnu Blood Bank"],
        "Bhadohi (Sant Ravidas Nagar)": ["Bhadohi District Hospital Blood Bank", "Red Cross Society Blood Bank", "Shree Ram Blood Bank"],
        "Bijnor": ["Bijnor District Hospital Blood Bank", "Red Cross Society Blood Bank", "Sai Blood Bank"],
        "Budaun": ["Budaun District Hospital Blood Bank", "Red Cross Society Blood Bank", "Shree Vishnu Blood Bank"],
        "Bulandshahr": ["Bulandshahr District Hospital Blood Bank", "Red Cross Society Blood Bank", "Shree Ganesh Blood Bank"],
        "Chandauli": ["Chandauli District Hospital Blood Bank", "Red Cross Society Blood Bank", "Shree Vishnu Blood Bank"],
        "Chitrakoot": ["Chitrakoot District Hospital Blood Bank", "Red Cross Society Blood Bank", "Sai Blood Bank"],
        "Deoria": ["Deoria District Hospital Blood Bank", "Red Cross Society Blood Bank", "Shree Ganesh Blood Bank"],
        "Etah": ["Etah District Hospital Blood Bank", "Red Cross Society Blood Bank", "Shree Ram Blood Bank"],
        "Etawah": ["Etawah District Hospital Blood Bank", "Red Cross Society Blood Bank", "Shree Vishnu Blood Bank"],
        "Farrukhabad": ["Farrukhabad District Hospital Blood Bank", "Red Cross Society Blood Bank", "Sai Blood Bank"],
        "Fatehpur": ["Fatehpur District Hospital Blood Bank", "Red Cross Society Blood Bank", "Shree Vishnu Blood Bank"],
        "Firozabad": ["Firozabad District Hospital Blood Bank", "Red Cross Society Blood Bank", "Shree Ram Blood Bank"],
        "Gautam Buddha Nagar (Noida)": ["Noida Blood Bank", "Apollo Hospital Blood Bank",  "Fortis Hospital Blood Bank",  "Max Super Speciality Hospital Blood Bank", "Bramh Kumari’s Blood Donation Camp", "Sharda Hospital Blood Bank", "DRDO Blood Bank" ],
        "Ghaziabad": ["Ghaziabad District Hospital Blood Bank", "Red Cross Society Blood Bank", "Sai Blood Bank"],
        "Ghazipur": ["Ghazipur District Hospital Blood Bank", "Red Cross Society Blood Bank", "Shree Vishnu Blood Bank"],
        "Gonda": ["Gonda District Hospital Blood Bank", "Red Cross Society Blood Bank", "Sai Blood Bank"],
        "Gorakhpur": ["Gorakhpur District Hospital Blood Bank", "Red Cross Society Blood Bank", "Shree Ganesh Blood Bank"],
        "Hamirpur": ["Hamirpur District Hospital Blood Bank", "Red Cross Society Blood Bank", "Shree Vishnu Blood Bank"],
        "Hapur": ["Hapur District Hospital Blood Bank", "Red Cross Society Blood Bank", "Shree Ram Blood Bank"],
        "Hardoi": ["Hardoi District Hospital Blood Bank", "Red Cross Society Blood Bank", "Sai Blood Bank"],
        "Hathras": ["Hathras District Hospital Blood Bank", "Red Cross Society Blood Bank", "Shree Vishnu Blood Bank"],
        "Jalaun": ["Jalaun District Hospital Blood Bank", "Red Cross Society Blood Bank", "Shree Ganesh Blood Bank"],
        "Jaunpur": ["Jaunpur District Hospital Blood Bank", "Red Cross Society Blood Bank", "Sai Blood Bank"],
        "Jhansi": ["Jhansi District Hospital Blood Bank", "Red Cross Society Blood Bank", "Shree Vishnu Blood Bank"],
        "Kannauj": ["Kannauj District Hospital Blood Bank", "Red Cross Society Blood Bank", "Shree Ram Blood Bank"],
        "Kasganj": ["Kasganj District Hospital Blood Bank", "Red Cross Society Blood Bank", "Shree Ganesh Blood Bank"],
        "Kaushambi": ["Kaushambi District Hospital Blood Bank", "Red Cross Society Blood Bank", "Sai Blood Bank"],
        "Kheri (Lakhimpur Kheri)": ["Kheri District Hospital Blood Bank", "Red Cross Society Blood Bank", "Shree Vishnu Blood Bank"],
        "Kushinagar": ["Kushinagar District Hospital Blood Bank", "Red Cross Society Blood Bank", "Shree Ram Blood Bank"],
        "Lalitpur": ["Lalitpur District Hospital Blood Bank", "Red Cross Society Blood Bank", "Sai Blood Bank"],
        "Maharajganj": ["Maharajganj District Hospital Blood Bank", "Red Cross Society Blood Bank", "Shree Vishnu Blood Bank"],
        "Mahoba": ["Mahoba District Hospital Blood Bank", "Red Cross Society Blood Bank", "Shree Ganesh Blood Bank"],
        "Mainpuri": ["Mainpuri District Hospital Blood Bank", "Red Cross Society Blood Bank", "Sai Blood Bank"],
        "Mathura": ["Mathura District Hospital Blood Bank", "Red Cross Society Blood Bank", "Shree Vishnu Blood Bank"],
        "Mau": ["Mau District Hospital Blood Bank", "Red Cross Society Blood Bank", "Shree Ram Blood Bank"],
        "Meerut": ["Meerut District Hospital Blood Bank", "Red Cross Society Blood Bank", "Shree Vishnu Blood Bank"],
        "Mirzapur": ["Mirzapur District Hospital Blood Bank", "Red Cross Society Blood Bank", "Shree Ganesh Blood Bank"],
        "Moradabad": ["Moradabad District Hospital Blood Bank", "Red Cross Society Blood Bank", "Sai Blood Bank"],
        "Muzaffarnagar": ["Muzaffarnagar District Hospital Blood Bank", "Red Cross Society Blood Bank", "Shree Vishnu Blood Bank"],
        "Pilibhit": ["Pilibhit District Hospital Blood Bank", "Red Cross Society Blood Bank", "Sai Blood Bank"],
        "Pratapgarh": ["Pratapgarh District Hospital Blood Bank", "Red Cross Society Blood Bank", "Shree Ram Blood Bank"],
        "Rae Bareli": ["Rae Bareli District Hospital Blood Bank", "Red Cross Society Blood Bank", "Shree Vishnu Blood Bank"],
        "Rampur": ["Rampur District Hospital Blood Bank", "Red Cross Society Blood Bank", "Shree Ram Blood Bank"],
        "Saharanpur": ["Saharanpur District Hospital Blood Bank", "Red Cross Society Blood Bank", "Satyam Blood Bank"],
        "Sambhal": ["Sambhal District Hospital Blood Bank", "Red Cross Society Blood Bank", "Shree Ganesh Blood Bank"],
        "Sant Kabir Nagar": ["Sant Kabir Nagar District Hospital Blood Bank", "Red Cross Society Blood Bank", "Shree Ram Blood Bank"],
        "Shahjahanpur": ["Shahjahanpur District Hospital Blood Bank", "Red Cross Society Blood Bank", "Shree Vishnu Blood Bank"],
        "Shamli": ["Shamli District Hospital Blood Bank", "Red Cross Society Blood Bank", "Sai Blood Bank"],
        "Shravasti": ["Shravasti District Hospital Blood Bank", "Red Cross Society Blood Bank", "Shree Ram Blood Bank"],
        "Siddharthnagar": ["Siddharthnagar District Hospital Blood Bank", "Red Cross Society Blood Bank", "Shree Ganesh Blood Bank"],
        "Sitapur": ["Sitapur District Hospital Blood Bank", "Red Cross Society Blood Bank", "Satyam Blood Bank"],
        "Sonbhadra": ["Sonbhadra District Hospital Blood Bank", "Red Cross Society Blood Bank", "Shree Ram Blood Bank"],
        "Sultanpur": ["Sultanpur District Hospital Blood Bank", "Red Cross Society Blood Bank", "Shree Vishnu Blood Bank" ],
        "Unnao": ["Unnao District Hospital Blood Bank", "Red Cross Society Blood Bank", "Sai Blood Bank"]       
    },
    "Haryana": {
        "Gurugram": ["Gurugram Blood Bank", "Fortis Memorial Research Institute Blood Bank", "Medanta - The Medicity Blood Bank", "Gurugram Civil Hospital Blood Bank", "Sanjeevani Blood Bank", "Apollo Cradle Blood Bank"],
        "Faridabad": ["Faridabad Blood Bank", "Government Medical College Blood Bank", "Asian Institute of Medical Sciences Blood Bank", "Indira Gandhi Institute of Medical Sciences (IGIMS) Blood Bank", "Apollo Hospital Blood Bank"],
"Panipat": ["Panipat Blood Bank", "Red Cross Blood Bank", "Apollo Hospitals Blood Bank", "Life Saver Blood Bank", "Government Blood Bank"],
"Hisar": ["Hisar District Hospital Blood Bank", "Red Cross Society Blood Bank", "Sai Blood Bank"],
"Jhajjar": ["Jhajjar District Hospital Blood Bank", "Red Cross Society Blood Bank", "Shree Ram Blood Bank"],
"Jind": ["Jind District Hospital Blood Bank", "Red Cross Society Blood Bank", "Shree Vishnu Blood Bank"],
"Kaithal": ["Kaithal District Hospital Blood Bank", "Red Cross Society Blood Bank", "Sai Blood Bank"],
"Karnal": ["Karnal District Hospital Blood Bank", "Red Cross Society Blood Bank", "Shree Ram Blood Bank"],
"Kurukshetra": ["Kurukshetra District Hospital Blood Bank", "Red Cross Society Blood Bank", "Sai Blood Bank"],
"Mahendragarh": ["Mahendragarh District Hospital Blood Bank", "Red Cross Society Blood Bank", "Shree Vishnu Blood Bank"],
"Narnaul": ["Narnaul District Hospital Blood Bank", "Red Cross Society Blood Bank", "Shree Ganesh Blood Bank"],
"Palwal": ["Palwal District Hospital Blood Bank", "Red Cross Society Blood Bank", "Sai Blood Bank"],
"Panchkula": ["Panchkula District Hospital Blood Bank", "Red Cross Society Blood Bank", "Shree Vishnu Blood Bank"],
"Rewari": ["Rewari District Hospital Blood Bank", "Red Cross Society Blood Bank", "Shree Vishnu Blood Bank"],
"Rohtak": ["Rohtak District Hospital Blood Bank", "Red Cross Society Blood Bank", "Shree Vishnu Blood Bank"],
"Sirsa": ["Sirsa District Hospital Blood Bank", "Red Cross Society Blood Bank", "Sai Blood Bank"],
"Sonipat": ["Sonipat District Hospital Blood Bank", "Red Cross Society Blood Bank", "Shree Ganesh Blood Bank"],
"Yamunanagar": ["Yamunanagar District Hospital Blood Bank", "Red Cross Society Blood Bank", "Sai Blood Bank"]

    },
    "Delhi":{
        "Central Delhi": ["Delhi Blood Bank Society", "AIIMS Blood Bank", "Indraprastha Apollo Hospitals Blood Bank"],
"East Delhi": ["Max Super Specialty Hospital Blood Bank", "Fortis C-DOC Blood Bank", "Satyabhama Blood Bank"],
"New Delhi": ["Delhi Blood Bank Society", "AIIMS Blood Bank", "Indraprastha Apollo Hospitals Blood Bank"],
"North Delhi": ["Delhi Blood Bank Society", "AIIMS Blood Bank", "Indraprastha Apollo Hospitals Blood Bank"],
"North East Delhi": ["Max Super Specialty Hospital Blood Bank", "Fortis C-DOC Blood Bank", "Satyabhama Blood Bank"],
"North West Delhi": ["BLK Super Specialty Hospital Blood Bank", "Maharaja Agrasen Hospital Blood Bank", "Columbia Asia Hospital Blood Bank"],
"Shahdara": ["Max Super Specialty Hospital Blood Bank", "Fortis C-DOC Blood Bank", "Satyabhama Blood Bank"],
"South Delhi": ["Max Super Specialty Hospital Blood Bank", "Fortis C-DOC Blood Bank", "Satyabhama Blood Bank"],
"South East Delhi": ["Max Super Specialty Hospital Blood Bank", "Fortis C-DOC Blood Bank", "Satyabhama Blood Bank"],
"South West Delhi": ["Max Super Specialty Hospital Blood Bank", "Fortis C-DOC Blood Bank", "Satyabhama Blood Bank"],
"West Delhi": ["BLK Super Specialty Hospital Blood Bank", "Maharaja Agrasen Hospital Blood Bank", "Columbia Asia Hospital Blood Bank"]
    },
    "Maharashtra": {
        "Aurangabad": ["Aurangabad Blood Bank", "Dr. N. K. Agrawal Blood Bank"],
"Beed": ["Beed District Blood Bank", "Red Cross Society Blood Bank", "Sai Blood Bank"],
"Bhandara": ["Bhandara District Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
"Buldhana": ["Buldhana District Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
"Chandrapur": ["Chandrapur District Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
"Dhule": ["Dhule District Blood Bank", "Red Cross Society Blood Bank", "Sai Blood Bank"],
"Gadchiroli": ["Gadchiroli District Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
"Gondia": ["Gondia District Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
"Hingoli": ["Hingoli District Blood Bank", "Red Cross Society Blood Bank", "Sai Blood Bank"],
"Jalna": ["Jalna District Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
"Kolhapur": ["Kolhapur Blood Bank", "Ruby Hall Clinic Blood Bank", "Shree Vishnu Blood Bank"],
"Latur": ["Latur District Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
"Nagpur": ["Blood Bank at Government Medical College", "Maharashtra Blood Bank", "Indira Gandhi Medical College Blood Bank"],
"Nashik": ["Nashik District Blood Bank", "Red Cross Society Blood Bank", "Sai Blood Bank"],
"Nandurbar": ["Nandurbar District Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
"Nanded": ["Nanded District Blood Bank", "Red Cross Society Blood Bank", "Sai Blood Bank"],
"Navi Mumbai": ["Navi Mumbai Blood Bank", "Fortis Memorial Research Institute Blood Bank", "Medanta Blood Bank"],
"Osmanabad": ["Osmanabad District Blood Bank", "Red Cross Society Blood Bank", "Sai Blood Bank"],
"Palghar": ["Palghar District Blood Bank", "Red Cross Society Blood Bank", "Sai Blood Bank"],
"Parbhani": ["Parbhani District Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
"Pune": ["Poona Blood Bank", "Smt. Kashibai Navale Medical College Blood Bank", "Ruby Hall Clinic Blood Bank"],
"Raigad": ["Raigad District Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
"Ratnagiri": ["Ratnagiri District Blood Bank", "Red Cross Society Blood Bank", "Sai Blood Bank"],
"Sangli": ["Sangli District Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
"Satara": ["Satara District Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
"Solapur": ["Solapur District Blood Bank", "Red Cross Society Blood Bank", "Sai Blood Bank"],
"Thane": ["Blood Bank at Jupiter Hospital", "Hiranandani Hospital Blood Bank", "Red Cross Society Blood Bank"],
"Wardha": ["Wardha District Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
"Washim": ["Washim District Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
"Yavatmal": ["Yavatmal District Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
"Sindhudurg": ["Sindhudurg District Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
"Ahmedabad": ["Nair Hospital Blood Bank", "KEM Hospital Blood Bank", "Sassoon General Hospital Blood Bank"],
"Akola": ["Akola Blood Bank", "Red Cross Society Blood Bank", "Shree Vishnu Blood Bank"],
"Amravati": ["Amravati Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
"Mumbai": ["Nair Hospital Blood Bank", "KEM Hospital Blood Bank", "Sassoon General Hospital Blood Bank", "Jaslok Hospital Blood Bank", "Lilavati Hospital Blood Bank"]
},

     "Andhra Pradesh":{
        "Anantapur": ["Anantapur District Blood Bank", "Red Cross Society Blood Bank", "Sai Blood Bank"],
"Chittoor": ["Chittoor District Blood Bank", "Red Cross Society Blood Bank", "Sri Venkateshwara Blood Bank"],
"East Godavari": ["East Godavari Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
"Guntur": ["Guntur District Blood Bank", "Red Cross Society Blood Bank", "Sai Blood Bank"],
"Krishna": ["Krishna District Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
"Kurnool": ["Kurnool District Blood Bank", "Red Cross Society Blood Bank", "Sai Blood Bank"],
"Prakasam": ["Prakasam District Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
"Srikakulam": ["Srikakulam District Blood Bank", "Red Cross Society Blood Bank", "Sai Blood Bank"],
"Visakhapatnam": ["Visakhapatnam District Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
"Vizianagaram": ["Vizianagaram District Blood Bank", "Red Cross Society Blood Bank", "Sai Blood Bank"],
"West Godavari": ["West Godavari Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
"Hyderabad": ["Hyderabad District Blood Bank", "Osmania General Hospital Blood Bank", "Red Cross Society Blood Bank"],
"Khammam": ["Khammam District Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
"Mahbubnagar": ["Mahbubnagar District Blood Bank", "Red Cross Society Blood Bank", "Sai Blood Bank"],
"Nalgonda": ["Nalgonda District Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
"Rangareddy": ["Rangareddy District Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
"Warangal": ["Warangal District Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
"Nizamabad": ["Nizamabad District Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
"Medak": ["Medak District Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"]

     },
     "Arunachal Pradesh": {
    "Tawang": ["Tawang District Blood Bank", "Red Cross Society Blood Bank"],
    "West Kameng": ["West Kameng District Blood Bank", "Red Cross Society Blood Bank"],
    "East Kameng": ["East Kameng District Blood Bank", "Red Cross Society Blood Bank"],
    "Papum Pare": ["Papum Pare District Blood Bank", "Red Cross Society Blood Bank"],
    "Lower Subansiri": ["Lower Subansiri District Blood Bank", "Red Cross Society Blood Bank"],
    "Upper Subansiri": ["Upper Subansiri District Blood Bank", "Red Cross Society Blood Bank"],
    "West Siang": ["West Siang District Blood Bank", "Red Cross Society Blood Bank"],
    "East Siang": ["East Siang District Blood Bank", "Red Cross Society Blood Bank"],
    "Siang": ["Siang District Blood Bank", "Red Cross Society Blood Bank"],
    "Changlang": ["Changlang District Blood Bank", "Red Cross Society Blood Bank"],
    "Lohit": ["Lohit District Blood Bank", "Red Cross Society Blood Bank"],
    "Namsai": ["Namsai District Blood Bank", "Red Cross Society Blood Bank"],
    "Lower Dibang Valley": ["Lower Dibang Valley District Blood Bank", "Red Cross Society Blood Bank"],
    "Upper Dibang Valley": ["Upper Dibang Valley District Blood Bank", "Red Cross Society Blood Bank"],
    "Kurung Kumey": ["Kurung Kumey District Blood Bank", "Red Cross Society Blood Bank"],
    "Kamle": ["Kamle District Blood Bank", "Red Cross Society Blood Bank"]
},
"Assam": {
    "Barpeta": ["Barpeta District Blood Bank", "Red Cross Society Blood Bank"],
    "Bongaigaon": ["Bongaigaon District Blood Bank", "Red Cross Society Blood Bank"],
    "Cachar": ["Cachar District Blood Bank", "Red Cross Society Blood Bank"],
    "Darrang": ["Darrang District Blood Bank", "Red Cross Society Blood Bank"],
    "Dibrugarh": ["Dibrugarh District Blood Bank", "Red Cross Society Blood Bank"],
    "Goalpara": ["Goalpara District Blood Bank", "Red Cross Society Blood Bank"],
    "Golaghat": ["Golaghat District Blood Bank", "Red Cross Society Blood Bank"],
    "Hailakandi": ["Hailakandi District Blood Bank", "Red Cross Society Blood Bank"],
    "Jorhat": ["Jorhat District Blood Bank", "Red Cross Society Blood Bank"],
    "Kamrup": ["Kamrup District Blood Bank", "Red Cross Society Blood Bank"],
    "Karbi Anglong": ["Karbi Anglong District Blood Bank", "Red Cross Society Blood Bank"],
    "Karimganj": ["Karimganj District Blood Bank", "Red Cross Society Blood Bank"],
    "Kokrajhar": ["Kokrajhar District Blood Bank", "Red Cross Society Blood Bank"],
    "Lakhimpur": ["Lakhimpur District Blood Bank", "Red Cross Society Blood Bank"],
    "Majuli": ["Majuli District Blood Bank", "Red Cross Society Blood Bank"],
    "Morigaon": ["Morigaon District Blood Bank", "Red Cross Society Blood Bank"],
    "Nagaon": ["Nagaon District Blood Bank", "Red Cross Society Blood Bank"],
    "Nalbari": ["Nalbari District Blood Bank", "Red Cross Society Blood Bank"],
    "Sivasagar": ["Sivasagar District Blood Bank", "Red Cross Society Blood Bank"],
    "Sonitpur": ["Sonitpur District Blood Bank", "Red Cross Society Blood Bank"],
    "Tinsukia": ["Tinsukia District Blood Bank", "Red Cross Society Blood Bank"],
    "Udalguri": ["Udalguri District Blood Bank", "Red Cross Society Blood Bank"]
},
"Bihar": {
    "Araria": ["Araria District Blood Bank", "Red Cross Society Blood Bank"],
    "Arwal": ["Arwal District Blood Bank", "Red Cross Society Blood Bank"],
    "Aurangabad": ["Aurangabad District Blood Bank", "Red Cross Society Blood Bank"],
    "Banka": ["Banka District Blood Bank", "Red Cross Society Blood Bank"],
    "Begusarai": ["Begusarai District Blood Bank", "Red Cross Society Blood Bank"],
    "Bhagalpur": ["Bhagalpur District Blood Bank", "Red Cross Society Blood Bank"],
    "Bhojpur": ["Bhojpur District Blood Bank", "Red Cross Society Blood Bank"],
    "Buxar": ["Buxar District Blood Bank", "Red Cross Society Blood Bank"],
    "Darbhanga": ["Darbhanga District Blood Bank", "Red Cross Society Blood Bank"],
    "East Champaran": ["East Champaran District Blood Bank", "Red Cross Society Blood Bank"],
    "Gaya": ["Gaya District Blood Bank", "Red Cross Society Blood Bank"],
    "Gopalganj": ["Gopalganj District Blood Bank", "Red Cross Society Blood Bank"],
    "Jamui": ["Jamui District Blood Bank", "Red Cross Society Blood Bank"],
    "Jehanabad": ["Jehanabad District Blood Bank", "Red Cross Society Blood Bank"],
    "Kaimur": ["Kaimur District Blood Bank", "Red Cross Society Blood Bank"],
    "Katihar": ["Katihar District Blood Bank", "Red Cross Society Blood Bank"],
    "Khagaria": ["Khagaria District Blood Bank", "Red Cross Society Blood Bank"],
    "Kishanganj": ["Kishanganj District Blood Bank", "Red Cross Society Blood Bank"],
    "Lakhisarai": ["Lakhisarai District Blood Bank", "Red Cross Society Blood Bank"],
    "Madhepura": ["Madhepura District Blood Bank", "Red Cross Society Blood Bank"],
    "Madhubani": ["Madhubani District Blood Bank", "Red Cross Society Blood Bank"],
    "Munger": ["Munger District Blood Bank", "Red Cross Society Blood Bank"],
    "Muzaffarpur": ["Muzaffarpur District Blood Bank", "Red Cross Society Blood Bank"],
    "Nalanda": ["Nalanda District Blood Bank", "Red Cross Society Blood Bank"],
    "Nawada": ["Nawada District Blood Bank", "Red Cross Society Blood Bank"],
    "Patna": ["Patna District Blood Bank", "Red Cross Society Blood Bank"],
    "Purnia": ["Purnia District Blood Bank", "Red Cross Society Blood Bank"],
    "Rohtas": ["Rohtas District Blood Bank", "Red Cross Society Blood Bank"],
    "Saharsa": ["Saharsa District Blood Bank", "Red Cross Society Blood Bank"],
    "Samastipur": ["Samastipur District Blood Bank", "Red Cross Society Blood Bank"],
    "Saran": ["Saran District Blood Bank", "Red Cross Society Blood Bank"],
    "Sheikhpura": ["Sheikhpura District Blood Bank", "Red Cross Society Blood Bank"],
    "Sheohar": ["Sheohar District Blood Bank", "Red Cross Society Blood Bank"],
    "SitaMadhy": ["SitaMadhy District Blood Bank", "Red Cross Society Blood Bank"],
    "Sitamarhi": ["Sitamarhi District Blood Bank", "Red Cross Society Blood Bank"],
    "Supaul": ["Supaul District Blood Bank", "Red Cross Society Blood Bank"],
    "Vaishali": ["Vaishali District Blood Bank", "Red Cross Society Blood Bank"],
    "West Champaran": ["West Champaran District Blood Bank", "Red Cross Society Blood Bank"]
},
"Chhattisgarh": {
    "Balod": ["Balod District Blood Bank", "Red Cross Society Blood Bank"],
    "Baloda Bazar": ["Baloda Bazar District Blood Bank", "Red Cross Society Blood Bank"],
    "Bastar": ["Bastar District Blood Bank", "Red Cross Society Blood Bank"],
    "Bilaspur": ["Bilaspur District Blood Bank", "Red Cross Society Blood Bank"],
    "Dantewada": ["Dantewada District Blood Bank", "Red Cross Society Blood Bank"],
    "Dhamtari": ["Dhamtari District Blood Bank", "Red Cross Society Blood Bank"],
    "Durg": ["Durg District Blood Bank", "Red Cross Society Blood Bank"],
    "Gariaband": ["Gariaband District Blood Bank", "Red Cross Society Blood Bank"],
    "Janjgir-Champa": ["Janjgir-Champa District Blood Bank", "Red Cross Society Blood Bank"],
    "Jashpur": ["Jashpur District Blood Bank", "Red Cross Society Blood Bank"],
    "Kabirdham": ["Kabirdham District Blood Bank", "Red Cross Society Blood Bank"],
    "Kanker": ["Kanker District Blood Bank", "Red Cross Society Blood Bank"],
    "Korba": ["Korba District Blood Bank", "Red Cross Society Blood Bank"],
    "Kondagaon": ["Kondagaon District Blood Bank", "Red Cross Society Blood Bank"],
    "Mahasamund": ["Mahasamund District Blood Bank", "Red Cross Society Blood Bank"],
    "Mungeli": ["Mungeli District Blood Bank", "Red Cross Society Blood Bank"],
    "Narayanpur": ["Narayanpur District Blood Bank", "Red Cross Society Blood Bank"],
    "Raigarh": ["Raigarh District Blood Bank", "Red Cross Society Blood Bank"],
    "Raipur": ["Raipur District Blood Bank", "Red Cross Society Blood Bank"],
    "Rajnandgaon": ["Rajnandgaon District Blood Bank", "Red Cross Society Blood Bank"],
    "Sukma": ["Sukma District Blood Bank", "Red Cross Society Blood Bank"],
    "Surajpur": ["Surajpur District Blood Bank", "Red Cross Society Blood Bank"],
    "Surguja": ["Surguja District Blood Bank", "Red Cross Society Blood Bank"]
},
"Goa": {
    "North Goa": ["North Goa District Blood Bank", "Red Cross Society Blood Bank", "Goa Medical College Blood Bank"],
    "South Goa": ["South Goa District Blood Bank", "Red Cross Society Blood Bank", "Margao Blood Bank"]
},
"Gujarat": {
    "Ahmedabad": ["Ahmedabad Blood Bank", "Sardar Vallabhbhai Patel Institute of Medical Sciences Blood Bank", "Shreeji Blood Bank", "Red Cross Society Blood Bank"],
    "Amreli": ["Amreli District Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Anand": ["Anand District Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Banaskantha": ["Banaskantha District Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Bharuch": ["Bharuch Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Bhavnagar": ["Bhavnagar Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Botad": ["Botad District Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Chhota Udepur": ["Chhota Udepur District Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Dahod": ["Dahod District Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Diu": ["Diu Blood Bank", "Red Cross Society Blood Bank"],
    "Daman": ["Daman Blood Bank", "Red Cross Society Blood Bank"],
    "Gandhinagar": ["Gandhinagar District Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Gir Somnath": ["Gir Somnath District Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Jamnagar": ["Jamnagar Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Junagadh": ["Junagadh District Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Kheda": ["Kheda District Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Kutch": ["Kutch District Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Mehsana": ["Mehsana District Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Morbi": ["Morbi District Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Narmada": ["Narmada District Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Navsari": ["Navsari Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Patan": ["Patan District Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Porbandar": ["Porbandar Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Rajkot": ["Rajkot Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Sabarkantha": ["Sabarkantha District Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Surendranagar": ["Surendranagar Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Surat": ["Surat Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Tapi": ["Tapi District Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Vadodara": ["Vadodara Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Valsad": ["Valsad Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"]
},
"Himachal Pradesh": {
    "Bilaspur": ["Bilaspur District Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Chamba": ["Chamba District Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Hamirpur": ["Hamirpur District Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Kangra": ["Kangra District Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Kullu": ["Kullu District Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Mandi": ["Mandi District Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Shimla": ["Shimla District Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Solan": ["Solan District Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Sirmaur": ["Sirmaur District Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Una": ["Una District Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"]
},
"Jharkhand": {
    "Bokaro": ["Bokaro Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Chatra": ["Chatra Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Deoghar": ["Deoghar Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Dhanbad": ["Dhanbad Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Dumka": ["Dumka Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "East Singhbhum": ["East Singhbhum Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Garhwa": ["Garhwa Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Giridih": ["Giridih Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Hazaribagh": ["Hazaribagh Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Jamtara": ["Jamtara Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Khunti": ["Khunti Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Koderma": ["Koderma Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Latehar": ["Latehar Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Lohardaga": ["Lohardaga Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Pakur": ["Pakur Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Palamu": ["Palamu Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Ranchi": ["Ranchi Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Sahibganj": ["Sahibganj Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Saraikela Kharsawan": ["Saraikela Kharsawan Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Simdega": ["Simdega Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "West Singhbhum": ["West Singhbhum Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"]
},
"Karnataka": {
    "Bagalkot": ["Bagalkot Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Ballari": ["Ballari Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Belagavi": ["Belagavi Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Bengaluru Rural": ["Bengaluru Rural Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Bengaluru Urban": ["Bengaluru Urban Blood Bank", "Bangalore Medical College Blood Bank", "Red Cross Society Blood Bank"],
    "Bidar": ["Bidar Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Chamarajanagar": ["Chamarajanagar Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Chikballapur": ["Chikballapur Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Chitradurga": ["Chitradurga Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Dakshina Kannada": ["Dakshina Kannada Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Davanagere": ["Davanagere Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Dharwad": ["Dharwad Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Gadag": ["Gadag Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Hassan": ["Hassan Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Haveri": ["Haveri Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Kodagu": ["Kodagu Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Kolar": ["Kolar Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Koppal": ["Koppal Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Mandya": ["Mandya Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Mysuru": ["Mysuru Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Raichur": ["Raichur Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Ramanagara": ["Ramanagara Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Shivamogga": ["Shivamogga Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Tumakuru": ["Tumakuru Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Udupi": ["Udupi Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Uttara Kannada": ["Uttara Kannada Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Vijayapura": ["Vijayapura Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Yadgir": ["Yadgir Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"]
},
"Kerala": {
    "Alappuzha": ["Alappuzha Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Ernakulam": ["Ernakulam Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Idukki": ["Idukki Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Kannur": ["Kannur Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Kasaragod": ["Kasaragod Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Kottayam": ["Kottayam Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Kozhikode": ["Kozhikode Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Malappuram": ["Malappuram Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Palakkad": ["Palakkad Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Pathanamthitta": ["Pathanamthitta Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Thiruvananthapuram": ["Thiruvananthapuram Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Thrissur": ["Thrissur Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Wayanad": ["Wayanad Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"]
},
"Madhya Pradesh": {
    "Agar Malwa": ["Agar Malwa Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Alirajpur": ["Alirajpur Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Anuppur": ["Anuppur Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Ashoknagar": ["Ashoknagar Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Balaghat": ["Balaghat Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Barwani": ["Barwani Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Betul": ["Betul Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Bhind": ["Bhind Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Bhopal": ["Bhopal Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Burhanpur": ["Burhanpur Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Chhatarpur": ["Chhatarpur Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Chhindwara": ["Chhindwara Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Damoh": ["Damoh Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Datia": ["Datia Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Dewas": ["Dewas Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Dhar": ["Dhar Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Dindori": ["Dindori Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Guna": ["Guna Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Gwalior": ["Gwalior Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Harda": ["Harda Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Hoshangabad": ["Hoshangabad Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Indore": ["Indore Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Jabalpur": ["Jabalpur Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Jhabua": ["Jhabua Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Katni": ["Katni Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Khandwa": ["Khandwa Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Mandla": ["Mandla Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Mandsaur": ["Mandsaur Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Morena": ["Morena Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Narsinghpur": ["Narsinghpur Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Neemuch": ["Neemuch Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Pachmarhi": ["Pachmarhi Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Rajgarh": ["Rajgarh Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Ratlam": ["Ratlam Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Rewa": ["Rewa Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Sagar": ["Sagar Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Satna": ["Satna Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Sehore": ["Sehore Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Seoni": ["Seoni Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Shahdol": ["Shahdol Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Shajapur": ["Shajapur Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Sheopur": ["Sheopur Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Sidhi": ["Sidhi Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Singrauli": ["Singrauli Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Tikamgarh": ["Tikamgarh Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Ujjain": ["Ujjain Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Vidisha": ["Vidisha Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"]
},
"Manipur": {
    "Imphal East": ["Imphal East Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Imphal West": ["Imphal West Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Bishnupur": ["Bishnupur Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Churachandpur": ["Churachandpur Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Chandel": ["Chandel Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Thoubal": ["Thoubal Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Senapati": ["Senapati Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Tamenglong": ["Tamenglong Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Ukhrul": ["Ukhrul Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Kangpokpi": ["Kangpokpi Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Peren": ["Peren Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"]
},
"Meghalaya": {
    "East Khasi Hills": ["East Khasi Hills Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "West Khasi Hills": ["West Khasi Hills Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "South Khasi Hills": ["South Khasi Hills Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Jaintia Hills": ["Jaintia Hills Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Ri-Bhoi": ["Ri-Bhoi Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "West Garo Hills": ["West Garo Hills Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "East Garo Hills": ["East Garo Hills Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "South Garo Hills": ["South Garo Hills Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "North Garo Hills": ["North Garo Hills Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"]
},
"Mizoram": {
    "Aizawl": ["Aizawl Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Champhai": ["Champhai Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Lunglei": ["Lunglei Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Siaha": ["Siaha Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Serchhip": ["Serchhip Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"]
},
"Nagaland": {
    "Dimapur": ["Dimapur Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Kohima": ["Kohima Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Mokokchung": ["Mokokchung Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Mon": ["Mon Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Phek": ["Phek Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Tuensang": ["Tuensang Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Zunheboto": ["Zunheboto Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"]
},
"Odisha": {
    "Bhubaneswar": ["Bhubaneswar Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Cuttack": ["Cuttack Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Berhampur": ["Berhampur Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Rourkela": ["Rourkela Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Sambalpur": ["Sambalpur Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Koraput": ["Koraput Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Balasore": ["Balasore Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Puri": ["Puri Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Jagatsinghpur": ["Jagatsinghpur Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Kendrapara": ["Kendrapara Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"]
},
"Punjab": {
    "Amritsar": ["Amritsar Blood Bank", "Red Cross Society Blood Bank", "Guru Nanak Dev Hospital Blood Bank"],
    "Ludhiana": ["Ludhiana Blood Bank", "Red Cross Society Blood Bank", "Dayanand Medical College Blood Bank"],
    "Chandigarh": ["Chandigarh Blood Bank", "Red Cross Society Blood Bank", "PGIMER Blood Bank"],
    "Jalandhar": ["Jalandhar Blood Bank", "Red Cross Society Blood Bank", "Civil Hospital Blood Bank"],
    "Patiala": ["Patiala Blood Bank", "Red Cross Society Blood Bank", "Rajindra Hospital Blood Bank"],
    "Bathinda": ["Bathinda Blood Bank", "Red Cross Society Blood Bank", "Civil Hospital Blood Bank"],
    "Hoshiarpur": ["Hoshiarpur Blood Bank", "Red Cross Society Blood Bank", "Civil Hospital Blood Bank"],
    "Ferozepur": ["Ferozepur Blood Bank", "Red Cross Society Blood Bank", "Civil Hospital Blood Bank"],
    "Moga": ["Moga Blood Bank", "Red Cross Society Blood Bank", "Civil Hospital Blood Bank"],
    "Sangrur": ["Sangrur Blood Bank", "Red Cross Society Blood Bank", "Civil Hospital Blood Bank"]
},
"Rajasthan": {
    "Jaipur": ["Jaipur Blood Bank", "Red Cross Society Blood Bank", "SMS Hospital Blood Bank", "Fortis Escorts Hospital Blood Bank"],
    "Udaipur": ["Udaipur Blood Bank", "Red Cross Society Blood Bank", "M.B. Hospital Blood Bank"],
    "Jodhpur": ["Jodhpur Blood Bank", "Red Cross Society Blood Bank", "Umaid Hospital Blood Bank"],
    "Kota": ["Kota Blood Bank", "Red Cross Society Blood Bank", "M.B.S. Hospital Blood Bank"],
    "Ajmer": ["Ajmer Blood Bank", "Red Cross Society Blood Bank", "Jawaharlal Nehru Hospital Blood Bank"],
    "Bikaner": ["Bikaner Blood Bank", "Red Cross Society Blood Bank", "PBM Hospital Blood Bank"],
    "Alwar": ["Alwar Blood Bank", "Red Cross Society Blood Bank", "Government Hospital Blood Bank"],
    "Tonk": ["Tonk Blood Bank", "Red Cross Society Blood Bank", "Civil Hospital Blood Bank"],
    "Sikar": ["Sikar Blood Bank", "Red Cross Society Blood Bank", "Civil Hospital Blood Bank"],
    "Churu": ["Churu Blood Bank", "Red Cross Society Blood Bank", "Civil Hospital Blood Bank"]
},
"Sikkim": {
    "East Sikkim": ["Sikkim State Blood Transfusion Council", "Red Cross Society Blood Bank", "STNM Hospital Blood Bank"],
    "West Sikkim": ["Red Cross Society Blood Bank", "District Hospital Blood Bank", "Singtam Hospital Blood Bank"],
    "South Sikkim": ["Red Cross Society Blood Bank", "Jorethang Hospital Blood Bank", "Namchi District Hospital Blood Bank"],
    "North Sikkim": ["Red Cross Society Blood Bank", "Mangan Hospital Blood Bank"]
},
"Tamil Nadu": {
    "Chennai": ["Government Blood Bank", "Red Cross Society Blood Bank", "Apollo Hospitals Blood Bank", "Fortis Malar Hospital Blood Bank", "Madras Medical Mission Blood Bank"],
    "Coimbatore": ["Coimbatore Blood Bank", "Red Cross Society Blood Bank", "GKNM Hospital Blood Bank", "Sri Ramakrishna Hospital Blood Bank"],
    "Madurai": ["Madurai Blood Bank", "Red Cross Society Blood Bank", "Rajaji Hospital Blood Bank", "Meenakshi Mission Hospital Blood Bank"],
    "Salem": ["Salem Blood Bank", "Red Cross Society Blood Bank", "Government Hospital Blood Bank", "Sri Gokulam Hospital Blood Bank"],
    "Trichy": ["Trichy Blood Bank", "Red Cross Society Blood Bank", "K.A.P. Viswanatham Government Medical College Blood Bank"],
    "Tirunelveli": ["Tirunelveli Blood Bank", "Red Cross Society Blood Bank", "Tirunelveli Medical College Blood Bank"],
    "Vellore": ["Christian Medical College Blood Bank", "Red Cross Society Blood Bank", "Vellore Government Medical College Blood Bank"],
    "Erode": ["Erode Blood Bank", "Red Cross Society Blood Bank", "Sri Ramakrishna Hospital Blood Bank"],
    "Tanjore": ["Tanjore Blood Bank", "Red Cross Society Blood Bank", "Government Hospital Blood Bank"],
    "Cuddalore": ["Cuddalore Blood Bank", "Red Cross Society Blood Bank", "Government Hospital Blood Bank"]
},
"Telangana": {
    "Hyderabad": ["Hyderabad District Blood Bank", "Osmania General Hospital Blood Bank", "Red Cross Society Blood Bank", "Nizam’s Institute of Medical Sciences Blood Bank", "Apollo Hospitals Blood Bank"],
    "Khammam": ["Khammam District Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Mahbubnagar": ["Mahbubnagar District Blood Bank", "Red Cross Society Blood Bank", "Sai Blood Bank"],
    "Nalgonda": ["Nalgonda District Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Rangareddy": ["Rangareddy District Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Warangal": ["Warangal District Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Nizamabad": ["Nizamabad District Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Medak": ["Medak District Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"]
},
"Tripura": {
    "Agartala": ["Agartala Blood Bank", "Red Cross Society Blood Bank", "Tripura State Blood Transfusion Council Blood Bank"],
    "Unakoti": ["Unakoti District Blood Bank", "Red Cross Society Blood Bank"],
    "South Tripura": ["South Tripura Blood Bank", "Red Cross Society Blood Bank"],
    "West Tripura": ["West Tripura Blood Bank", "Red Cross Society Blood Bank"]
},
"Uttarakhand": {
    "Dehradun": ["Dehradun District Blood Bank", "Red Cross Society Blood Bank", "Max Super Speciality Hospital Blood Bank", "Doon Hospital Blood Bank"],
    "Nainital": ["Nainital District Blood Bank", "Red Cross Society Blood Bank", "Haldwani Blood Bank"],
    "Haridwar": ["Haridwar District Blood Bank", "Red Cross Society Blood Bank", "Maya Hospital Blood Bank"],
    "Udhamsingh Nagar": ["Udhamsingh Nagar District Blood Bank", "Red Cross Society Blood Bank", "Life Saver Blood Bank"],
    "Almora": ["Almora District Blood Bank", "Red Cross Society Blood Bank"],
    "Pithoragarh": ["Pithoragarh District Blood Bank", "Red Cross Society Blood Bank"],
    "Chamoli": ["Chamoli District Blood Bank", "Red Cross Society Blood Bank"],
    "Rudraprayag": ["Rudraprayag District Blood Bank", "Red Cross Society Blood Bank"],
    "Tehri Garhwal": ["Tehri Garhwal District Blood Bank", "Red Cross Society Blood Bank"],
    "Bageshwar": ["Bageshwar District Blood Bank", "Red Cross Society Blood Bank"],
    "Pauri Garhwal": ["Pauri Garhwal District Blood Bank", "Red Cross Society Blood Bank"]
},
"West Bengal": {
    "Kolkata": ["Kolkata Blood Bank", "Susrut Eye Foundation and Research Centre Blood Bank", "Calcutta Medical College Blood Bank", "Apollo Gleneagles Hospitals Blood Bank", "Fortis Hospital Blood Bank"],
    "Howrah": ["Howrah District Blood Bank", "Red Cross Society Blood Bank", "Shree Shree Blood Bank"],
    "North 24 Parganas": ["North 24 Parganas District Blood Bank", "Red Cross Society Blood Bank", "Sree Krishna Blood Bank"],
    "South 24 Parganas": ["South 24 Parganas District Blood Bank", "Red Cross Society Blood Bank", "Bengal Blood Bank"],
    "Murshidabad": ["Murshidabad District Blood Bank", "Red Cross Society Blood Bank", "Murshidabad Medical College Blood Bank"],
    "Nadia": ["Nadia District Blood Bank", "Red Cross Society Blood Bank", "Krishnanagar Blood Bank"],
    "Hooghly": ["Hooghly District Blood Bank", "Red Cross Society Blood Bank", "Santanaghat Blood Bank"],
    "Purulia": ["Purulia District Blood Bank", "Red Cross Society Blood Bank", "Purulia Sadar Hospital Blood Bank"],
    "Bankura": ["Bankura District Blood Bank", "Red Cross Society Blood Bank", "Bankura Sammilani Medical College Blood Bank"],
    "Paschim Medinipur": ["Paschim Medinipur District Blood Bank", "Red Cross Society Blood Bank", "Midnapore Medical College Blood Bank"],
    "Purba Medinipur": ["Purba Medinipur District Blood Bank", "Red Cross Society Blood Bank", "Kolar Medical College Blood Bank"],
    "Birbhum": ["Birbhum District Blood Bank", "Red Cross Society Blood Bank", "Rampurhat Blood Bank"],
    "Jalpaiguri": ["Jalpaiguri District Blood Bank", "Red Cross Society Blood Bank", "Jalpaiguri Medical College Blood Bank"],
    "Cooch Behar": ["Cooch Behar District Blood Bank", "Red Cross Society Blood Bank", "Cooch Behar Sadar Hospital Blood Bank"],
    "Alipurduar": ["Alipurduar District Blood Bank", "Red Cross Society Blood Bank"]
},
};

function updateDistricts() {
    const state = document.getElementById('state').value;
    const districtSelect = document.getElementById('district');
    
    // Clear previous district options
    districtSelect.innerHTML = '<option value="">Select a district</option>';
    
    // Add new options based on the selected state
    if (state && districts[state]) {
        Object.keys(districts[state]).forEach(district => {
            const option = document.createElement('option');
            option.value = district;
            option.text = district;
            districtSelect.add(option);
        });
    }
}

function showCenters() {
    const state = document.getElementById('state').value;
    const district = document.getElementById('district').value;

    let result = document.getElementById('result');
    result.innerHTML = ''; // Clear previous results

    if (state && district) {
        if (districts[state] && districts[state][district]) {
            const centers = districts[state][district];
            result.innerHTML = `<h2>Available Blood Donation Centers in ${district}, ${state}:</h2>`;
            
            // Create a table
            let table = '<table border="1" cellpadding="10" cellspacing="0" style="margin: 0 auto; border-collapse: collapse;">';
            table += '<tr><th>Blood Donation Center</th></tr>'; // Table header

            centers.forEach(center => {
                table += `<tr><td>${center}</td></tr>`;
            });

            table += '</table>';
            result.innerHTML += table;
        } else {
            result.innerHTML = `<p>No centers found in ${district}, ${state}.</p>`;
        }
    } else {
        result.innerHTML = '<p>Please select both state and district.</p>';
    }
}

function clearResults() {
    document.getElementById('state').value = '';
    document.getElementById('district').innerHTML = '<option value="">Select a district</option>';
    document.getElementById('result').innerHTML = '';
}

